user nginx;
worker_processes 1;
pid /run/nginx.pid;
error_log stderr notice;

events {
    worker_connections 64;
}

http {
    access_log off;
    default_type text/plain;
    sendfile on;
    keepalive_timeout 5;

    include /etc/nginx/conf.d/*.conf;
}
